# Generated by Django 3.2.6 on 2021-08-13 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_allergyproducts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergyproducts',
        ),
    ]
