# Generated by Django 3.2.6 on 2021-08-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_allergyproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergyproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.allergy')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products')),
            ],
            options={
                'db_table': 'allergyproducts',
            },
        ),
    ]
