# Generated by Django 3.2.6 on 2021-08-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_allergyproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='product_id',
            new_name='products',
        ),
    ]
