# Generated by Django 3.2.6 on 2021-08-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210813_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergyproducts',
            old_name='allergy_id',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='allergyproducts',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='nutrtion_id',
            new_name='nutrtion',
        ),
    ]
