# Generated by Django 3.2.6 on 2021-08-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210813_0742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergyproducts',
            new_name='Allergyproduct',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Nutritions',
            new_name='Nutrition',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='allergy',
            table='allergys',
        ),
    ]
