# Generated by Django 3.2.6 on 2021-08-13 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210813_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrtion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.nutrition'),
        ),
    ]
