# Generated by Django 3.2.6 on 2021-08-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_nutrtion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergy',
            field=models.ManyToManyField(related_name='products', through='products.Allergyproduct', to='products.Allergy'),
        ),
    ]
